spring.application.name=Transparence
server.port=8080

server.forward-headers-strategy=framework
spring.jpa.open-in-view=false

jwt.secret=MinhaChaveSimplesParaAprenderJWT123456
jwt.expiration=3600000
